version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current

parameters:
  name:
    type: string
    default: "Mona"
    description: "Name of the person to greet"

jobs:
  greet:
    executor: default
    parameters:
      is_happy:
        type: boolean
    steps:
      - checkout
      - run:
          name: Greet someone
          command: |
            echo "Hello, << pipeline.parameters.name >>! Are you happy? << parameters.is_happy >>"

  farewell:
    executor: default
    parameters:
      farewell_message:
        type: enum
        enum: ["Goodbye", "See you later", "Take care"]
    steps:
      - checkout
      - run:
          name: Farewell someone
          command: |
            echo "<< parameters.farewell_message >>, << pipeline.parameters.name >>!"

workflows:
  greet-and-farewell:
    jobs:
      - greet:
          is_happy: << pipeline.parameters.is_happy >>