name: "Greet someone and Farewell v2"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        default: "Mona"
      farewell_message:
        description: "Select a farewell message"
        type: choice
        required: true
        options:
          - "Goodbye"
          - "See you later"
          - "Take care"
      is_happy:
        type: boolean
        description: "Is the person happy?"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Greet someone
        run: echo "Hello, ${{ github.event.inputs.name }}! Are you happy? ${{ github.event.inputs.is_happy }}"

  farewell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Farewell someone
        run: echo "${{ github.event.inputs.farewell_message }}, ${{ github.event.inputs.name }}!"